

import { NgModule } from "@angular/core";
import {
    MatProgressBarModule,
    MatButtonModule, 
    MatCheckboxModule,
    MatToolbarModule,
    MatButtonToggleModule,
    MatMenuModule,
    MatIconModule,
    MatBadgeModule,
    MatSidenavModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatInputModule,
    MatCardModule,
    MatSelectModule,
    MatGridListModule,
    MatDatepickerModule,
    MatSliderModule,
    MatDividerModule,
    MatListModule,
    MatChipsModule,
    MatDialogModule,
    MatAutocompleteModule,
    MatSlideToggleModule,
    MatTableModule,
    MatTooltipModule
} from '@angular/material';

@NgModule({
    imports: [
        MatTableModule,
        MatAutocompleteModule,
        MatButtonModule, 
        MatCheckboxModule,
        MatToolbarModule,
        MatButtonToggleModule,
        MatMenuModule,
        MatIconModule,
        MatBadgeModule,
        MatSidenavModule,
        MatExpansionModule,
        MatFormFieldModule,
        MatInputModule,
        MatCardModule,
        MatSelectModule,
        MatGridListModule,
        MatDatepickerModule,
        MatSliderModule,
        MatDividerModule,
        MatListModule,
        MatChipsModule,
        MatDialogModule,
        MatSlideToggleModule,
        MatTooltipModule,
        MatProgressBarModule
    ],
    exports: [
        MatTooltipModule,
        MatProgressBarModule,
        MatTableModule,
        MatSlideToggleModule,
        MatButtonModule, 
        MatCheckboxModule,
        MatAutocompleteModule,
        MatToolbarModule,
        MatButtonToggleModule,
        MatMenuModule,
        MatIconModule,
        MatBadgeModule,
        MatSidenavModule,
        MatExpansionModule,
        MatFormFieldModule,
        MatInputModule,
        MatCardModule,
        MatSelectModule,
        MatGridListModule,
        MatDatepickerModule,
        MatSliderModule,
        MatDividerModule,
        MatListModule,
        MatChipsModule,
        MatDialogModule
    ]
})
export class MaterialModule{

}